version: '3'

services :
  web:
    container_name: web
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    ports:
        - '8000:80'
    volumes:
      - ./:/var/www/html/

  database:
    container_name: database
    build:
      context: .
      dockerfile: .docker/database/Dockerfile
    volumes:
      - ./.database/data:/var/lib/postgresql/data:cached
      - ./.database/logs:/var/log:cached
    environment:
      POSTGRES_DB: ${DB_DATABASE:-postgres}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8'
      TZ: Asia/Tokyo
    ports:
      - ${DB_PORT}:5432
